name: Hourly

on:
    workflow_dispatch:

jobs:
    Run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 19

            - name: multiline
              run: |
                  echo Salam
                  pwd
