# Step 1: Use an official Node.js runtime as a parent image
FROM node:26-alpine

# Step 2: Set the working directory inside the container
WORKDIR /opt

# Step 7: Define the command to run your app
CMD [ "env" ]
