# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish

on:
    workflow_dispatch:
    release:
        types: [created]
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            # # Setup Python
            # - name: Set up Python
            #   uses: actions/setup-python@v3
            #   with:
            #       python-version: "3.12" # Specify the Python version you need

            # - uses: actions/setup-node@v3
            #   with:
            #       node-version: 18
            # - run: npm -g install pnpm

            # - run: pnpm install

            - run: echo "GITHUB_REF_NAME $GITHUB_REF_NAME"

            - run: docker build . -t ngmaibulat/mailgw:$GITHUB_REF_NAME

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # - run: docker tag ngmaibulat/mailgw ngmaibulat/mailgw

            - name: Tag Docker image
              run: docker tag ngmaibulat/mailgw:$GITHUB_REF_NAME ngmaibulat/mailgw:latest

            - name: List Docker Images
              run: docker images

            # - name: Tag Docker image
            #   run: docker tag ngmaibulat/mailgw:$GITHUB_REF_NAME ngmaibulat/mailgw:other

            - run: docker push --all-tags ngmaibulat/mailgw
