# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish

on:
    workflow_dispatch:
    release:
        types: [created]
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm -g install pnpm

            - run: pnpm install

            - name: Extract Git tag
              id: extract_tag
              run: echo "::set-output name=tag::${{ github.ref/refs\/tags\// }}"

            - run: docker build . -t ngmaibulat/mailgw

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - run: docker tag ngmaibulat/mailgw ngmaibulat/mailgw

            - name: Tag Docker image
              run: docker tag ngmaibulat/mailgw ngmaibulat/mailgw:${{ steps.extract_tag.outputs.tag }}
            #   run: docker tag my-image:latest my-registry/my-image:${{ steps.extract_tag.outputs.tag }}

            - run: docker push ngmaibulat/mailgw
