# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish

on:
    workflow_dispatch:
    release:
        types: [created]
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm -g install pnpm
            - run: pnpm install
            - run: docker build . -t ngmaibulat/mailgw
            - run: env
              env:
                  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
                  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                  AWS_REGION: ${{vars.AWS_REGION}}
                  S3_BUCKET: ${{vars.S3_BUCKET}}
